### ISSUE TITLE
Demo #1 gives 404 error

### ISSUE THREAD

**Issue by HelloChrisLowe** [mpcodemonkey/mvre#1]
Reproduction steps:
1) Visit https://mpcodemonkey.github.io/mvre/examples/01-Webgl2-and-Scenegraph/ on any browser
2) Open console

![image](https://cloud.githubusercontent.com/assets/2397972/22362679/58c288c6-e419-11e6-8703-2881f14a6c00.png)

**Comment by mpcodemonkey** [comment]
There was a capitalization error in the main.js file, which led to renderer not being loaded. This issue has now been fixed.
